import pgvector.sqlalchemy

"""Initial schema

Revision ID: 7e3d4f24139f
Revises: 
Create Date: 2026-08-12 22:38:28.815984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e3d4f24139f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('github_id', sa.Integer(), nullable=False),
    sa.Column('github_username', sa.String(length=255), nullable=False),
    sa.Column('github_avatar_url', sa.String(length=500), nullable=True),
    sa.Column('github_token', sa.String(length=255), nullable=False),
    sa.Column('github_installation_id', sa.Integer(), nullable=True),
    sa.Column('slack_webhook_url', sa.String(length=500), nullable=True),
    sa.Column('discord_webhook_url', sa.String(length=500), nullable=True),
    sa.Column('email_alerts_enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_github_id'), 'users', ['github_id'], unique=True)
    op.create_index(op.f('ix_users_github_installation_id'), 'users', ['github_installation_id'], unique=False)
    op.create_table('repos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('installation_id', sa.Integer(), nullable=True),
    sa.Column('webhook_id', sa.Integer(), nullable=True),
    sa.Column('is_indexed', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('slack_webhook_url', sa.String(length=500), nullable=True),
    sa.Column('discord_webhook_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repos_installation_id'), 'repos', ['installation_id'], unique=False)
    op.create_index(op.f('ix_repos_user_id'), 'repos', ['user_id'], unique=False)
    op.create_table('document_embeddings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('chunk_id', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('meta_json', sa.Text(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_embeddings_file_path'), 'document_embeddings', ['file_path'], unique=False)
    op.create_index(op.f('ix_document_embeddings_repo_id'), 'document_embeddings', ['repo_id'], unique=False)
    op.create_table('scans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=False),
    sa.Column('commit_sha', sa.String(length=40), nullable=False),
    sa.Column('branch', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('vulnerability_type', sa.String(length=100), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('vulnerable_file', sa.String(length=500), nullable=True),
    sa.Column('exploit_output', sa.Text(), nullable=True),
    sa.Column('patch_diff', sa.Text(), nullable=True),
    sa.Column('pr_url', sa.String(length=500), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('original_code', sa.Text(), nullable=True),
    sa.Column('exploit_script', sa.Text(), nullable=True),
    sa.Column('findings_json', sa.Text(), nullable=True),
    sa.Column('current_agent', sa.String(length=50), nullable=True),
    sa.Column('agent_message', sa.String(length=500), nullable=True),
    sa.Column('patch_attempts', sa.Integer(), nullable=True),
    sa.Column('is_regression', sa.Boolean(), nullable=True),
    sa.Column('original_fix_scan_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['original_fix_scan_id'], ['scans.id'], ),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scans_commit_sha'), 'scans', ['commit_sha'], unique=False)
    op.create_index(op.f('ix_scans_repo_id'), 'scans', ['repo_id'], unique=False)
    op.create_index(op.f('ix_scans_status'), 'scans', ['status'], unique=False)
    op.create_table('vuln_signatures',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('vuln_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('fix_commit', sa.String(length=40), nullable=True),
    sa.Column('fix_scan_id', sa.Integer(), nullable=True),
    sa.Column('fixed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fix_scan_id'], ['scans.id'], ),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vuln_signatures_repo_id'), 'vuln_signatures', ['repo_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vuln_signatures_repo_id'), table_name='vuln_signatures')
    op.drop_table('vuln_signatures')
    op.drop_index(op.f('ix_scans_status'), table_name='scans')
    op.drop_index(op.f('ix_scans_repo_id'), table_name='scans')
    op.drop_index(op.f('ix_scans_commit_sha'), table_name='scans')
    op.drop_table('scans')
    op.drop_index(op.f('ix_document_embeddings_repo_id'), table_name='document_embeddings')
    op.drop_index(op.f('ix_document_embeddings_file_path'), table_name='document_embeddings')
    op.drop_table('document_embeddings')
    op.drop_index(op.f('ix_repos_user_id'), table_name='repos')
    op.drop_index(op.f('ix_repos_installation_id'), table_name='repos')
    op.drop_table('repos')
    op.drop_index(op.f('ix_users_github_installation_id'), table_name='users')
    op.drop_index(op.f('ix_users_github_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
