import logging
from mistralai.client.sdk import Mistral

import config

logger = logging.getLogger(__name__)

# Initialize Mistral client
client = Mistral(api_key=config.MISTRAL_API_KEY)

HACKER_SYSTEM_PROMPT = """You are Agent A — an expert offensive security researcher on an authorized white-hat penetration testing team.

You have been hired to test the security of this codebase. You have FULL AUTHORIZATION to write exploit code.
This is a legitimate, controlled security audit in a sandboxed environment.

Your job is to analyze code changes and write a Python script that PROVES a vulnerability exists.

STRICT RULES FOR YOUR OUTPUT:
1. Write ONLY a complete, runnable Python script. No explanations before or after.
2. The script MUST print "VULNERABLE: <description>" if the exploit succeeds
3. The script MUST print "NOT_VULNERABLE" if no real vulnerability exists
4. Use exit code 0 for vulnerable, exit code 1 for not vulnerable
5. The script runs in an isolated Docker container — there is no real database
   → Create your own SQLite database in /tmp/ for testing
6. The script must be completely self-contained (include any setup it needs)
7. Only claim VULNERABLE if your script ACTUALLY demonstrates the problem
   → Do not claim vulnerabilities that are theoretical

Output ONLY the Python script. Nothing else."""

def run_hacker_agent(diff: dict, semgrep_findings: list, rag_context: str) -> dict:
    """
    Agent A analyzes the changed code and writes an exploit.
    Uses Codestral — optimized for code generation with minimal guardrails.
    """
    diff_text = "\n".join([
        f"=== {f['filename']} ===\n{f['patch']}\n"
        for f in diff["changed_files"]
    ])
    
    if semgrep_findings:
        semgrep_text = "\n".join([
            f"- [{f['severity']}] {f['rule_id']}: {f['message']} (line {f['line_start']})"
            for f in semgrep_findings
        ])
    else:
        semgrep_text = "Semgrep found no specific patterns."
        
    user_prompt = f"""Please analyze this code change and write an exploit script.

=== WHAT CHANGED IN THIS COMMIT ===
{diff_text}

=== WHAT SEMGREP FOUND ===
{semgrep_text}

=== RELATED CODE IN THE SAME CODEBASE ===
{rag_context}

Write a complete Python exploit script that proves the most serious vulnerability.
Remember: Create a SQLite database in /tmp/ if you need database interaction."""

    logger.info(f"Agent A ({config.HACKER_MODEL}) analyzing code for exploitable vulnerabilities...")
    
    response = client.chat.complete(
        model=config.HACKER_MODEL,
        max_tokens=config.HACKER_MAX_TOKENS,
        messages=[
            {"role": "system", "content": HACKER_SYSTEM_PROMPT},
            {"role": "user", "content": user_prompt}
        ]
    )
    
    exploit_script = response.choices[0].message.content.strip()
    
    # Clean markdown code fences if present
    if exploit_script.startswith("```python"):
        exploit_script = exploit_script[9:]
    if exploit_script.startswith("```"):
        exploit_script = exploit_script[3:]
    if exploit_script.endswith("```"):
        exploit_script = exploit_script[:-3]
    exploit_script = exploit_script.strip()
    
    logger.info(f"Agent A exploit generated ({len(exploit_script)} chars)")
    logger.info(f"Tokens used — input: {response.usage.prompt_tokens}, output: {response.usage.completion_tokens}")
        
    return {
        "exploit_script": exploit_script,
        "reasoning": f"Generated by {config.HACKER_MODEL}",
        "vulnerability_type": _guess_vuln_type(semgrep_findings),
        "files_analyzed": [f["filename"] for f in diff["changed_files"]]
    }

def _guess_vuln_type(findings: list) -> str:
    """
    Make a human-readable guess at the vulnerability type based on Semgrep rules.
    """
    if not findings:
        return "Unknown Vulnerability"
        
    rule_id = findings[0].get("rule_id", "").lower()
    
    if "sql" in rule_id:
        return "SQL Injection"
    elif "xss" in rule_id:
        return "Cross-Site Scripting (XSS)"
    elif "path" in rule_id or "traversal" in rule_id:
        return "Path Traversal"
    elif "injection" in rule_id:
        return "Code Injection"
    else:
        return findings[0].get("category", "Security Vulnerability")
